/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Vector3 } from '@react-three/fiber'
import { omit } from 'lodash-es'

type GLTFResult = GLTF & {
    nodes: {
        FrameLR: THREE.Mesh
        MonitorLR: THREE.Mesh
        FrameC: THREE.Mesh
        MonitorC: THREE.Mesh
        FrameTL: THREE.Mesh
        MonitorTL: THREE.Mesh
        FrameTR: THREE.Mesh
        MonitorTR: THREE.Mesh
        MonitorLL: THREE.Mesh
        FrameLL: THREE.Mesh
    }
    materials: {}
}


// Fixed offset from monitor to frame
const frameOffset: THREE.Vector3Tuple = [0.016, 0.002, -0.038]; // Example: from LR

export function getFramePosition(monitorPosition: THREE.Vector3Tuple): THREE.Vector3Tuple {
    if (!monitorPosition) return [0, 0, 0];
    return [
        monitorPosition[0] + frameOffset[0],
        monitorPosition[1] + frameOffset[1],
        monitorPosition[2] + frameOffset[2],
    ];
}
export const getFrameProps = (props: THREE.Mesh) => {
    const position = getFramePosition(props?.position);

    return ({
        ...omit(props, ['material']),
        position,
    })
}

const MODEL_PATH = '/webgl/models/mg-monitors.glb'

export function Monitors({ monitors, materials, ...props }: React.JSX.IntrinsicElements['group'] & {
    materials?: [THREE.Material, THREE.Material, THREE.Material]
    monitors: THREE.Mesh[]
}) {
    const { nodes, _materials } = useGLTF(MODEL_PATH) as any as GLTFResult

    return (
        <group {...props} dispose={null}>
            <mesh
                name="FrameLR"
                castShadow
                receiveShadow
                geometry={nodes.FrameLR.geometry}
                material={nodes.FrameLR.material}
                // position={[-1.16, -1.823, -0.726]}
                // {...monitors?.[0] ?? {}} // TODO: need to compute right position
                // position={getFramePosition(monitors?.[0].position)}
                {...getFrameProps(monitors?.[0])}

            />
            <mesh
                name="MonitorLR"
                castShadow
                receiveShadow
                geometry={nodes.MonitorLR.geometry}
                // material={nodes.MonitorLR.material}
                // material={materials?.[0] ?? nodes.MonitorLL.material}
                position={[-1.176, -1.825, -0.688]}
                // {...(monitors?.left ?? {})}
                {...monitors?.[0] ?? {}}
            />
            <mesh
                name="FrameC"
                castShadow
                receiveShadow
                geometry={nodes.FrameC.geometry}
                material={nodes.FrameC.material}
                // position={[-0.002, 0.001, 0.002]}
                // {...monitors?.[1] ?? {}}
                // position={getFramePosition(monitors?.[1].position)}
                {...getFrameProps(monitors?.[1])}

            />
            <mesh
                name="MonitorC"
                castShadow
                receiveShadow
                geometry={nodes.MonitorC.geometry}
                // material={nodes.MonitorC.material}
                material={materials?.[1] ?? nodes.MonitorC.material}
                position={[0.001, -0.007, 0.103]}
                // {...(monitors?.center ?? {})}
                {...monitors?.[1] ?? {}}


            />
            {/* <mesh
                name="FrameTL"
                castShadow
                receiveShadow
                geometry={nodes.FrameTL.geometry}
                material={nodes.FrameTL.material}
                position={[0.964, 2.662, 0.306]}
            />
            <mesh
                name="MonitorTL"
                castShadow
                receiveShadow
                geometry={nodes.MonitorTL.geometry}
                material={nodes.MonitorTL.material}
                position={[0.977, 2.661, 0.377]}
            /> */}
            {/* <mesh
                name="FrameTR"
                castShadow
                receiveShadow
                geometry={nodes.FrameTR.geometry}
                material={nodes.FrameTR.material}
                position={[-1.645, 2.261, -0.706]}
            />
            <mesh
                name="MonitorTR"
                castShadow
                receiveShadow
                geometry={nodes.MonitorTR.geometry}
                material={nodes.MonitorTR.material}
                position={[-1.653, 2.26, -0.679]}
            /> */}
            <mesh
                name="MonitorLL"
                castShadow
                receiveShadow
                geometry={nodes.MonitorLL.geometry}
                // material={nodes.MonitorLL.material}
                // material={materials?.[2] ?? nodes.MonitorLR.material}
                position={[0.952, -1.774, -0.282]}
                {...monitors?.[2] ?? {}}

            />
            <mesh
                name="FrameLL"
                castShadow
                receiveShadow
                geometry={nodes.FrameLL.geometry}
                material={nodes.FrameLL.material}
                // position={[0.929, -1.769, -0.389]}
                // {...(monitors?.right ?? {})}
                // {...monitors?.[2] ?? {}}
                // position={getFramePosition(monitors?.[2].position)}
                {...getFrameProps(monitors?.[2])}
            />
        </group>
    )
}

useGLTF.preload(MODEL_PATH)
