/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useControls } from 'leva'
import { useCablesTextures } from './useCableTextures'

type GLTFResult = GLTF & {
    nodes: {
        AnimatedCable001: THREE.Mesh
        AnimatedCable002: THREE.Mesh
        AnimatedCable003: THREE.Mesh
        AnimatedCable004: THREE.Mesh
        StaticCable009: THREE.Mesh
        StaticCable001: THREE.Mesh
        StaticCable002: THREE.Mesh
        StaticCable003: THREE.Mesh
        StaticCable004: THREE.Mesh
        StaticCable005: THREE.Mesh
        StaticCable006: THREE.Mesh
        StaticCable007: THREE.Mesh
        StaticCable008: THREE.Mesh
    }
    materials: {}
}

// TODO: reusable component for cables ceiling and floor, just need type to pass to controls name
const CableMaterial: React.FC = () => {
    const [colorMap, normalMap, roughnessMap, displacementMap] = useCablesTextures()

    const materialProps = useControls("Scene/Objects/CablesFloor/Material", {
        color: "#0d0d0d",
        metalness: { value: 0.0, min: 0, max: 1, step: 0.01 },
        roughness: { value: 0.6, min: 0, max: 1, step: 0.01 },
        opacity: { value: 1, min: 0, max: 1, step: 0.01 },
        transparent: false,
        envMapIntensity: { value: 0.3, min: 0, max: 5, step: 0.1 },
        emissive: "#0d0d0d",
        emissiveIntensity: { value: 2, min: 0, max: 10 },
        displacementScale: { value: 0.015, min: 0, max: 5 }
    }, { collapsed: true })

    return (
        <meshStandardMaterial
            map={colorMap}
            normalMap={normalMap}
            roughnessMap={roughnessMap}
            displacementMap={displacementMap}
            {...materialProps}
        />
    )
}

const MODEL_PATH = '/webgl/models/mg-cables-floor-compressed.glb'
export function CablesFloor(props: React.JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(MODEL_PATH) as any as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable001.geometry}
                // material={nodes.AnimatedCable001.material}
                position={[-5.264, 0.077, 5.037]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable002.geometry}
                // material={nodes.AnimatedCable002.material}
                position={[4.562, 0.099, 0.972]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable003.geometry}
                // material={nodes.AnimatedCable003.material}
                position={[4.498, 0.115, -4.721]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable004.geometry}
                // material={nodes.AnimatedCable004.material}
                position={[-4.475, 0.141, -3.531]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable009.geometry}
                // material={nodes.StaticCable009.material}
                position={[-0.274, 0.098, -0.464]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable001.geometry}
                // material={nodes.StaticCable001.material}
                position={[-3.988, 0.086, 0.582]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable002.geometry}
                // material={nodes.StaticCable002.material}
                position={[5.755, 0.074, 0.405]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable003.geometry}
                // material={nodes.StaticCable003.material}
                position={[2.273, 0.086, 0.27]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable004.geometry}
                // material={nodes.StaticCable004.material}
                position={[-2.817, 0.093, 0.417]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable005.geometry}
                // material={nodes.StaticCable005.material}
                position={[1.32, 0.144, 1.335]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable006.geometry}
                // material={nodes.StaticCable006.material}
                position={[3.015, 0.078, 1.376]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable007.geometry}
                // material={nodes.StaticCable007.material}
                position={[-2.661, 0.076, 1.088]}
            >
                <CableMaterial />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable008.geometry}
                // material={nodes.StaticCable008.material}
                position={[-1.626, 0.133, 1.657]}
            >
                <CableMaterial />
            </mesh>
        </group>
    )
}

useGLTF.preload(MODEL_PATH)
