/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        AnimatedCable001: THREE.Mesh
        AnimatedCable002: THREE.Mesh
        AnimatedCable003: THREE.Mesh
        AnimatedCable004: THREE.Mesh
        StaticCable009: THREE.Mesh
        StaticCable001: THREE.Mesh
        StaticCable002: THREE.Mesh
        StaticCable003: THREE.Mesh
        StaticCable004: THREE.Mesh
        StaticCable005: THREE.Mesh
        StaticCable006: THREE.Mesh
        StaticCable007: THREE.Mesh
        StaticCable008: THREE.Mesh
    }
    materials: {}
}

const MODEL_PATH = '/webgl/models/mg-cables-floor.glb'
export function CablesFloor(props: React.JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(MODEL_PATH) as any as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable001.geometry}
                material={nodes.AnimatedCable001.material}
                position={[-5.264, 0.077, 5.037]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable002.geometry}
                material={nodes.AnimatedCable002.material}
                position={[4.562, 0.099, 0.972]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable003.geometry}
                material={nodes.AnimatedCable003.material}
                position={[4.498, 0.115, -4.721]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.AnimatedCable004.geometry}
                material={nodes.AnimatedCable004.material}
                position={[-4.475, 0.141, -3.531]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable009.geometry}
                material={nodes.StaticCable009.material}
                position={[-0.274, 0.098, -0.464]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable001.geometry}
                material={nodes.StaticCable001.material}
                position={[-3.988, 0.086, 0.582]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable002.geometry}
                material={nodes.StaticCable002.material}
                position={[5.755, 0.074, 0.405]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable003.geometry}
                material={nodes.StaticCable003.material}
                position={[2.273, 0.086, 0.27]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable004.geometry}
                material={nodes.StaticCable004.material}
                position={[-2.817, 0.093, 0.417]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable005.geometry}
                material={nodes.StaticCable005.material}
                position={[1.32, 0.144, 1.335]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable006.geometry}
                material={nodes.StaticCable006.material}
                position={[3.015, 0.078, 1.376]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable007.geometry}
                material={nodes.StaticCable007.material}
                position={[-2.661, 0.076, 1.088]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.StaticCable008.geometry}
                material={nodes.StaticCable008.material}
                position={[-1.626, 0.133, 1.657]}
            />
        </group>
    )
}

useGLTF.preload(MODEL_PATH)
