/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Text, TextProps, useCursor, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { getSharedUniforms } from '../chemicals/shaders/shaderMaterials'
import { useMaterials } from './useMaterials'

type GLTFResult = GLTF & {
    nodes: {
        FrameLR: THREE.Mesh
        MonitorLR: THREE.Mesh
        FrameC: THREE.Mesh
        MonitorC: THREE.Mesh
        FrameTL: THREE.Mesh
        MonitorTL: THREE.Mesh
        FrameTR: THREE.Mesh
        MonitorTR: THREE.Mesh
        MonitorLL: THREE.Mesh
        FrameLL: THREE.Mesh
    }
    materials: {}
}


// Fixed offset from monitor to frame
const frameOffset: THREE.Vector3Tuple = [0.016, 0.002, -0.038]; // Example: from LR

function getFramePosition(monitorPosition: THREE.Vector3Tuple): THREE.Vector3Tuple {
    if (!monitorPosition) return [0, 0, 0];
    return [
        monitorPosition[0] + frameOffset[0],
        monitorPosition[1] + frameOffset[1],
        monitorPosition[2] + frameOffset[2],
    ];
}

const MODEL_PATH = '/webgl/models/mg-monitors-compressed.glb'

const MONITORS_POSITION: THREE.Vector3Tuple[] = [
    [-2, 0, -1],
    [0, 0, 0],
    [2, 0, -1],
]

const MonitorFrameMaterial = () => {
    return (
        <meshStandardMaterial
            metalness={0.6}
            roughness={0.4}
            color="#2a2a2a"
            envMapIntensity={0.5}
        />
    )
}

interface MonitorData {
    name: 'DOPAMINE' | 'OXYTOCIN' | 'SEROTONIN';
    color: string;
    position: THREE.Vector3Tuple;
    description: string;
    ref: React.RefObject<THREE.Mesh<THREE.BufferGeometry<THREE.NormalBufferAttributes, THREE.BufferGeometryEventMap>, THREE.Material | THREE.Material[], THREE.Object3DEventMap> | null>;
    material: THREE.ShaderMaterial;
}


interface HormoneTextProps {
    monitor: MonitorData,
    type?: 'title' | 'description'
}

const HormoneText: React.FC<HormoneTextProps> = ({
    monitor,
    type = 'title'
}) => {
    const sharedProps: Omit<TextProps, 'children'> = {
        font: "/fonts/Inter-Medium.woff",
        castShadow: true
    }

    const props: Omit<TextProps, 'children'> = type === 'title' ? {
        ...sharedProps,
        fontSize: 0.25,
        anchorX: 'center',
        anchorY: 'middle',
        color: monitor.color,
        position: [monitor.position[0], monitor.position[1] + (monitor.name === 'OXYTOCIN' ? 2.25 : 2), monitor.position[2]]
    }
        : {
            ...sharedProps,
            fontSize: 0.12,
            color: '#fff',
            maxWidth: 2,
            textAlign: 'center',
            position: [monitor.position[0], monitor.position[1] - 1.5, monitor.position[2] + 1.5]
        }

    const text = type === "title" ? monitor.name : monitor.description

    return (
        <Text
            {...props}
        >
            {text}
            <meshBasicMaterial color={monitor.color} toneMapped={false} />
        </Text>
    )
}

export function Monitors(props: React.JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF(MODEL_PATH) as any as GLTFResult

    const dopamineMeshRef = useRef<THREE.Mesh>(null);
    const oxytocinMeshRef = useRef<THREE.Mesh>(null);
    const serotoninMeshRef = useRef<THREE.Mesh>(null);

    const { dopamineMaterial, oxytocinMaterial, serotoninMaterial } = useMaterials()

    //  correct the inverted UV coordinates in model
    useEffect(() => {
        // Fix dopamine monitor (MonitorLR)
        if (nodes.MonitorLR?.geometry) {
            const uvs = nodes.MonitorLR.geometry.attributes.uv
            for (let i = 0; i < uvs.count; i++) {
                uvs.setY(i, 1.0 - uvs.getY(i))
            }
            uvs.needsUpdate = true
        }

        // Fix oxytocin monitor (MonitorC)
        if (nodes.MonitorC?.geometry) {
            const uvs = nodes.MonitorC.geometry.attributes.uv
            for (let i = 0; i < uvs.count; i++) {
                uvs.setY(i, 1.0 - uvs.getY(i))
            }
            uvs.needsUpdate = true
        }

        // Fix serotonin monitor (MonitorLL)
        if (nodes.MonitorLL?.geometry) {
            const uvs = nodes.MonitorLL.geometry.attributes.uv
            for (let i = 0; i < uvs.count; i++) {
                uvs.setY(i, 1.0 - uvs.getY(i))
            }
            uvs.needsUpdate = true
        }
    }, [nodes])

    const [isHovered, setIsHovered] = useState(false)
    const [hoveredMonitorName, setHoveredMonitorName] = useState<MonitorData['name'] | null>(null)
    useCursor(isHovered)

    const onPointerEnterMonitor = (name: MonitorData['name']) => {
        setIsHovered(true);
        setHoveredMonitorName(name)
    }
    const onPointerLeaveMonitor = (name: MonitorData['name']) => {
        setIsHovered(false);
        setHoveredMonitorName(null)
    }

    const monitorData: MonitorData[] = [
        {
            name: 'DOPAMINE',
            color: getSharedUniforms('dopamine').u_baseColor.value,
            position: MONITORS_POSITION[0],
            description: 'Excitement • Reward • Motivation',
            ref: dopamineMeshRef,
            material: dopamineMaterial
        },
        {
            name: 'OXYTOCIN',
            color: getSharedUniforms('oxytocin').u_baseColor.value,
            position: MONITORS_POSITION[1],
            description: 'Connection • Warmth • Love',
            ref: oxytocinMeshRef,
            material: oxytocinMaterial
        },
        {
            name: 'SEROTONIN',
            color: getSharedUniforms('serotonin').u_baseColor.value,
            position: MONITORS_POSITION[2],
            description: 'Calmness • Well-being • Introspection',
            ref: serotoninMeshRef,
            material: serotoninMaterial
        }
    ]

    return (
        <group
            position={[0, 2, 0]}
            {...props}
            dispose={null}
        >
            <mesh
                name="FrameLR"
                castShadow
                receiveShadow
                geometry={nodes.FrameLR.geometry}
                material={nodes.FrameLR.material}
                position={getFramePosition(MONITORS_POSITION[0])}
            >
                <MonitorFrameMaterial />
            </mesh>
            <mesh
                ref={dopamineMeshRef}
                name="MonitorLR"
                castShadow
                receiveShadow
                geometry={nodes.MonitorLR.geometry}
                material={dopamineMaterial}
                position={MONITORS_POSITION[0]}
                // onPointerEnter={() => onPointerEnterMonitor('DOPAMINE')}
                // onPointerLeave={() => onPointerLeaveMonitor}
            />
            <mesh
                name="FrameC"
                castShadow
                receiveShadow
                geometry={nodes.FrameC.geometry}
                material={nodes.FrameC.material}
                position={getFramePosition(MONITORS_POSITION[1])}
            >
                <MonitorFrameMaterial />
            </mesh>
            <mesh
                ref={oxytocinMeshRef}
                name="MonitorC"
                castShadow
                receiveShadow
                geometry={nodes.MonitorC.geometry}
                material={oxytocinMaterial}
                position={MONITORS_POSITION[1]}
                // onPointerEnter={() => onPointerEnterMonitor('OXYTOCIN')}
                // onPointerLeave={() => onPointerLeaveMonitor}

            // rotation={[Math.PI, 0, 0]}  // fix geometry, need side: DoubleSide in material
            />
            {/* <mesh
                name="FrameTL"
                castShadow
                receiveShadow
                geometry={nodes.FrameTL.geometry}
                material={nodes.FrameTL.material}
                position={[0.964, 2.662, 0.306]}
            />
            <mesh
                name="MonitorTL"
                castShadow
                receiveShadow
                geometry={nodes.MonitorTL.geometry}
                material={nodes.MonitorTL.material}
                position={[0.977, 2.661, 0.377]}
            /> */}
            {/* <mesh
                name="FrameTR"
                castShadow
                receiveShadow
                geometry={nodes.FrameTR.geometry}
                material={nodes.FrameTR.material}
                position={[-1.645, 2.261, -0.706]}
            />
            <mesh
                name="MonitorTR"
                castShadow
                receiveShadow
                geometry={nodes.MonitorTR.geometry}
                material={nodes.MonitorTR.material}
                position={[-1.653, 2.26, -0.679]}
            /> */}
            <mesh
                ref={serotoninMeshRef}
                name="MonitorLL"
                castShadow
                receiveShadow
                geometry={nodes.MonitorLL.geometry}
                material={serotoninMaterial}
                position={MONITORS_POSITION[2]}
                // onPointerEnter={() => onPointerEnterMonitor('SEROTONIN')}
                // onPointerLeave={() => onPointerLeaveMonitor}

            />
            <mesh
                name="FrameLL"
                castShadow
                receiveShadow
                geometry={nodes.FrameLL.geometry}
                material={nodes.FrameLL.material}
                position={getFramePosition(MONITORS_POSITION[2])}
            >
                <MonitorFrameMaterial />
            </mesh>



            {/* {monitorData.map((monitor) => (
                <HormoneText key={monitor.name} monitor={monitor} />
            ))}
            {hoveredMonitorName && (
                <HormoneText monitor={monitorData.find((monitor) => monitor.name === hoveredMonitorName)!} type="description" />
            )} */}

            <pointLight
                position={MONITORS_POSITION[0]}
                color="#ff6b9d"
                intensity={1.5}  // Increased from 0.3
                distance={6}     // Increased from 3
                decay={2}        // Add decay for realistic falloff
            />
            <pointLight
                position={MONITORS_POSITION[1]}
                color="#ff8844"
                intensity={1.5}
                distance={6}
                decay={2}
            />
            <pointLight
                position={MONITORS_POSITION[2]}
                color="#6b7aff"
                intensity={1.5}
                distance={6}
                decay={2}
            />
        </group >
    )
}

useGLTF.preload(MODEL_PATH)
