/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Text, TextProps, useCursor, useGLTF, useTexture } from '@react-three/drei'
import { useControls } from 'leva'
import React, { useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { shaderUniformConfigs } from '../chemicals/shaders/shaderMaterials'
import { MONITOR_DIMENSIONS, useMaterials } from './useMaterials'
import { useFrame } from '@react-three/fiber'
import { easing } from 'maath'
import { HormoneNames, useStore } from '@/lib/store'
import { useShallow } from 'zustand/react/shallow'
import { useRouter } from 'next/navigation'
import { gsap } from 'gsap'
import { animateNavToPageFadeOut } from '@/lib/animations'

type GLTFResult = GLTF & {
    nodes: {
        FrameLR: THREE.Mesh
        MonitorLR: THREE.Mesh
        FrameC: THREE.Mesh
        MonitorC: THREE.Mesh
        FrameTL: THREE.Mesh
        MonitorTL: THREE.Mesh
        FrameTR: THREE.Mesh
        MonitorTR: THREE.Mesh
        MonitorLL: THREE.Mesh
        FrameLL: THREE.Mesh
    }
    materials: {}
}


// Fixed offset from monitor to frame
const frameOffset: THREE.Vector3Tuple = [0.016, 0.002, -0.038]; // Example: from LR

function getFramePosition(monitorPosition: THREE.Vector3Tuple): THREE.Vector3Tuple {
    if (!monitorPosition) return [0, 0, 0];
    return [
        monitorPosition[0] + frameOffset[0],
        monitorPosition[1] + frameOffset[1],
        monitorPosition[2] + frameOffset[2],
    ];
}

const MODEL_PATH = '/webgl/models/mg-monitors-compressed.glb'

const MONITORS_POSITION: THREE.Vector3Tuple[] = [
    [-2, 0, -1],
    [0, 0, 0],
    [2, 0, -1],
]

const MonitorFrameMaterial = () => {
    const [normalMap, roughnessMap, colorMap, metalnessMap] = useTexture([
        '/webgl/textures/monitors/Metal011_1K-JPG_NormalGL.jpg',
        '/webgl/textures/monitors/Metal011_1K-JPG_Roughness.jpg',
        '/webgl/textures/monitors/Metal011_1K-JPG_Color.jpg',
        '/webgl/textures/monitors/Metal011_1K-JPG_Metalness.jpg',
    ])

    const materialProps = useControls("Scene/Objects/Monitors/Frame Material", {
        color: "#2a2a2a",
        metalness: { value: 0.6, min: 0, max: 1, step: 0.01 },
        roughness: { value: 0.4, min: 0, max: 1, step: 0.01 },
        opacity: { value: 1, min: 0, max: 1, step: 0.01 },
        transparent: false,
        envMapIntensity: { value: 0.5, min: 0, max: 5, step: 0.1 },
        emissive: "#000000",
        emissiveIntensity: { value: 1, min: 0, max: 10 },
    })

    return (
        <meshStandardMaterial
            map={colorMap}
            normalMap={normalMap}
            roughnessMap={roughnessMap}
            metalnessMap={metalnessMap}
            {...materialProps}
        />
    )
}

interface MonitorData {
    name: HormoneNames;
    color: string;
    position: THREE.Vector3Tuple;
    ref: React.RefObject<THREE.Mesh<THREE.BufferGeometry<THREE.NormalBufferAttributes, THREE.BufferGeometryEventMap>, THREE.Material | THREE.Material[], THREE.Object3DEventMap> | null>;
    material: THREE.ShaderMaterial;
}


interface HormoneLabelProps {
    monitor: MonitorData,
    isHovered: boolean;
}

const HormoneLabel: React.FC<HormoneLabelProps> = ({
    monitor,
    isHovered,
}) => {
    const [x, y, z] = monitor.position;
    const position: THREE.Vector3Tuple = [x, y, z + 0.25]

    const getTextRotation = (monitorName: string): THREE.Vector3Tuple => {
        if (monitorName === 'DOPAMINE') return [0, -0.2, 0]
        if (monitorName === 'SEROTONIN') return [0, 0.2, 0]
        return [0, 0, 0]
    }

    const meshRef = useRef<THREE.Mesh>(null)
    const targetOpacity = useRef(0)

    const controls = useControls(`Scene/Texts/Label/${monitor.name}`, {
        rotation: { value: getTextRotation(monitor.name) },
        position: { value: position },
    })

    useFrame((_state, delta) => {
        if (!meshRef.current) return

        const target = isHovered ? 1 : 0
        easing.damp(targetOpacity, 'current', target, 0.3, delta)

        if (meshRef.current.material) {
            // @ts-ignore TODO: fix type
            meshRef.current.material.opacity = targetOpacity.current
            meshRef.current.visible = targetOpacity.current > 0.01
        }
    })

    return (
        <Text
            ref={meshRef}
            font="/fonts/Inter-Medium.woff"
            fontSize={0.25}
            anchorX="center"
            anchorY="middle"
            raycast={() => null}
            letterSpacing={-0.05}
            castShadow
            receiveShadow
            {...controls}
        >
            {monitor.name}
            <meshBasicMaterial
                color="#ffffff"
                toneMapped={false}
                transparent
                opacity={0}
            />
        </Text>
    )
}

export function Monitors(props: React.JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF(MODEL_PATH) as any as GLTFResult

    const dopamineMeshRef = useRef<THREE.Mesh>(null);
    const oxytocinMeshRef = useRef<THREE.Mesh>(null);
    const serotoninMeshRef = useRef<THREE.Mesh>(null);

    const { dopamineMaterial, oxytocinMaterial, serotoninMaterial } = useMaterials()

    // TODO: move to useFrame???
    //  correct the inverted UV coordinates in model
    // Clone and fix UVs immediately - runs once when nodes change
    const fixedGeometries = useMemo(() => {
        const fixUVs = (geometry: THREE.BufferGeometry) => {
            const cloned = geometry.clone()
            const uvs = cloned.attributes.uv
            for (let i = 0; i < uvs.count; i++) {
                uvs.setY(i, 1.0 - uvs.getY(i))
            }
            uvs.needsUpdate = true
            return cloned
        }

        return {
            MonitorLR: nodes.MonitorLR?.geometry ? fixUVs(nodes.MonitorLR.geometry) : null,
            MonitorC: nodes.MonitorC?.geometry ? fixUVs(nodes.MonitorC.geometry) : null,
            MonitorLL: nodes.MonitorLL?.geometry ? fixUVs(nodes.MonitorLL.geometry) : null,
        }
    }, [nodes])

    const [isHovered, setIsHovered] = useState(false)
    useCursor(isHovered)
    const [hoveredName, setHoveredName] = useStore(useShallow((state) => [state.hoveredName, state.setHoveredName]))

    const onPointerEnterMonitor = (name: MonitorData['name']) => {
        setIsHovered(true);
        setHoveredName(name)
    }
    const onPointerLeaveMonitor = () => {
        setIsHovered(false);
        setHoveredName(null)
    }

    const monitorData: MonitorData[] = [
        {
            name: 'DOPAMINE',
            color: shaderUniformConfigs.dopamine.baseColor,
            position: MONITORS_POSITION[0],
            ref: dopamineMeshRef,
            material: dopamineMaterial
        },
        {
            name: 'OXYTOCIN',
            color: shaderUniformConfigs.oxytocin.baseColor,
            position: MONITORS_POSITION[1],
            ref: oxytocinMeshRef,
            material: oxytocinMaterial
        },
        {
            name: 'SEROTONIN',
            color: shaderUniformConfigs.serotonin.baseColor,
            position: MONITORS_POSITION[2],
            ref: serotoninMeshRef,
            material: serotoninMaterial
        }
    ]



    const getCenteredPos = (position: THREE.Vector3Tuple, monitorPosition: 'left' | 'middle' | 'right'): THREE.Vector3Tuple => {
        const [x, y, z] = position;
        const monitorCenter = MONITOR_DIMENSIONS.WIDTH / 2

        let centeredX = x;
        if (monitorPosition === 'left') centeredX = x - monitorCenter;
        else if (monitorPosition === 'right') centeredX = x + monitorCenter;  // ✅ Add instead of subtract

        return [centeredX, y, z]
    }

    const pointLightDopamine = useControls("Scene/Lights/Point Dopamine", {
        position: { value: getCenteredPos(monitorData[0].position, 'left') },
        intensity: { value: 1.5, min: 0, max: 2 },
        distance: { value: 6, min: 0, max: 50 },
        decay: { value: 2, min: 0, max: 10 },
        castShadow: true,
        color: monitorData[0].color,
    })

    const pointLightOxytocin = useControls("Scene/Lights/Point Oxytocin", {
        position: { value: monitorData[1].position },
        intensity: { value: 1.5, min: 0, max: 2 },
        distance: { value: 6, min: 0, max: 50 },
        decay: { value: 2, min: 0, max: 10 },
        castShadow: true,
        color: monitorData[1].color,
    })

    const pointLightSerotonin = useControls("Scene/Lights/Point Serotonin", {
        position: { value: getCenteredPos(monitorData[2].position, 'right') },
        intensity: { value: 1.5, min: 0, max: 2 },
        distance: { value: 6, min: 0, max: 50 },
        decay: { value: 2, min: 0, max: 10 },
        castShadow: true,
        color: monitorData[2].color,
    })

    const router = useRouter();
    const onDoubleClick = (name: HormoneNames) => {
        setHoveredName(null);
        animateNavToPageFadeOut(router, `/${name.toLowerCase()}`)
    }

    return (
        <group
            position={[0, 2, 0]}
            {...props}
            dispose={null}
        >
            <mesh
                name="FrameLR"
                castShadow
                receiveShadow
                geometry={nodes.FrameLR.geometry}
                material={nodes.FrameLR.material}
                position={getFramePosition(MONITORS_POSITION[0])}
            >
                <MonitorFrameMaterial />
            </mesh>
            <mesh
                ref={dopamineMeshRef}
                name="MonitorLR"
                castShadow
                receiveShadow
                geometry={fixedGeometries.MonitorLR!}
                material={dopamineMaterial}
                position={MONITORS_POSITION[0]}
                onPointerEnter={() => onPointerEnterMonitor('DOPAMINE')}
                onPointerLeave={() => onPointerLeaveMonitor()}
                onDoubleClick={() => onDoubleClick('DOPAMINE')}
            />
            <mesh
                name="FrameC"
                castShadow
                receiveShadow
                geometry={nodes.FrameC.geometry}
                material={nodes.FrameC.material}
                position={getFramePosition(MONITORS_POSITION[1])}
            >
                <MonitorFrameMaterial />
            </mesh>
            <mesh
                ref={oxytocinMeshRef}
                name="MonitorC"
                castShadow
                receiveShadow
                geometry={fixedGeometries.MonitorC!}
                material={oxytocinMaterial}
                position={MONITORS_POSITION[1]}
                onPointerEnter={() => onPointerEnterMonitor('OXYTOCIN')}
                onPointerLeave={() => onPointerLeaveMonitor()}
                onDoubleClick={() => onDoubleClick('OXYTOCIN')}

            />
            {/* <mesh
                name="FrameTL"
                castShadow
                receiveShadow
                geometry={nodes.FrameTL.geometry}
                material={nodes.FrameTL.material}
                position={[0.964, 2.662, 0.306]}
            />
            <mesh
                name="MonitorTL"
                castShadow
                receiveShadow
                geometry={nodes.MonitorTL.geometry}
                material={nodes.MonitorTL.material}
                position={[0.977, 2.661, 0.377]}
            /> */}
            {/* <mesh
                name="FrameTR"
                castShadow
                receiveShadow
                geometry={nodes.FrameTR.geometry}
                material={nodes.FrameTR.material}
                position={[-1.645, 2.261, -0.706]}
            />
            <mesh
                name="MonitorTR"
                castShadow
                receiveShadow
                geometry={nodes.MonitorTR.geometry}
                material={nodes.MonitorTR.material}
                position={[-1.653, 2.26, -0.679]}
            /> */}
            <mesh
                ref={serotoninMeshRef}
                name="MonitorLL"
                castShadow
                receiveShadow
                geometry={fixedGeometries.MonitorLL!}
                material={serotoninMaterial}
                position={MONITORS_POSITION[2]}
                onPointerEnter={() => onPointerEnterMonitor('SEROTONIN')}
                onPointerLeave={() => onPointerLeaveMonitor()}
                onDoubleClick={() => onDoubleClick('SEROTONIN')}


            />
            <mesh
                name="FrameLL"
                castShadow
                receiveShadow
                geometry={nodes.FrameLL.geometry}
                material={nodes.FrameLL.material}
                position={getFramePosition(MONITORS_POSITION[2])}
            >
                <MonitorFrameMaterial />
            </mesh>

            <group name="Labels">
                {monitorData.map((monitor) => (
                    <HormoneLabel key={monitor.name} monitor={monitor} isHovered={
                        hoveredName === monitor.name
                    } />
                ))}
            </group>


            <group name="PointLights">
                <pointLight
                    {...pointLightDopamine}
                />
                <pointLight
                    {...pointLightOxytocin}
                />
                <pointLight
                    {...pointLightSerotonin}
                />
            </group>
        </group >
    )
}

useGLTF.preload(MODEL_PATH)
